openshift_cluster_content:
- object: projects
  content:
  - name: "Create the DEV and Stage Environments"
    file: "{{ inventory_dir }}/../projects/projects.yml"
    action: create
- object: deployments
  content:
  - name: "Deploy Jenkins"
    template: "openshift//jenkins-ephemeral"
    params: "{{ inventory_dir }}/../params/jenkins"
    namespace: liberty-dev
  - name: "Create PROD Cluster Credentials"
    template: "{{ inventory_dir }}/../templates/cluster-secret.yml"
    params: "{{ inventory_dir }}/../params/prod-credentials"
    namespace: liberty-dev
  - name: "Deploy Dev environment"
    template: "{{ inventory_dir }}/../templates/deployment.yml"
    params: "{{ inventory_dir }}/../params/deployment-dev"
  - name: "Deploy Stage environment"
    template: "{{ inventory_dir }}/../templates/deployment.yml"
    params: "{{ inventory_dir }}/../params/deployment-stage"
- object: builds
  content:
  - name: Apply Image Build"
    namespace: "liberty-dev"
    template: "{{ inventory_dir }}/../templates/jenkins-slave-image-mgmt-template.json"
    params: "{{ inventory_dir }}/../params/build-slave-dev"
  - name: "Deploy docker pipeline to Dev"
    template: "{{ inventory_dir }}/../templates/build.yml"
    params: "{{ inventory_dir }}/../params/build-dev"
